name = "SineTables"
uuid = "cd6dab6d-c555-4e2f-9f3e-18e1596ea3b4"
authors = ["Erik Buer"]
version = "0.1.2"

[deps]


[compat]
julia = "1.6"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter"]
